### ISSUE TITLE
No quiere aparecer el fake login

### ISSUE THREAD

**Issue by TacticalLettuce** [s4vitar/evilTrust#16]
Chavale, este programa es una pasada, pero cuando me conecto a la red pirateada, no me aparece el incio de sesion falso. Soluciones? Gracias de antemano

**Comment by LechugaTactica** [comment]
yghyjtyjfrydfjxsdthtrttxgfnfngfgnngfng

**Comment by TacticalLettuce** [comment]
Chavale, no os preocupeis, ya lo he solucionao. Solamente mata wpa_supplicant, y ala, problema resuelto. Gracias por este increible programa
