### ISSUE TITLE
Añadir habilidad

### ISSUE THREAD

**Issue by Dazmed707** [s4vitar/evilTrust#2]
Se podría añadir la habilidad de listar los dispositivos conectados hasta que introduzcan las credenciales.

**Comment by s4vitar** [comment]
Hmm, podría implementarse sí... no sería muy complejo, le doy una vuelta

**Comment by s4vitar** [comment]
Hecho, ahora la herramienta muestra el número de clientes conectados al AP en la fase de espera de obtención de credenciales
