### ISSUE TITLE
No termina de ejecutarse?

### ISSUE THREAD

**Issue by AlloyB** [s4vitar/evilTrust#33]
Buenas! soy relativamente nueva en esto y quería probar la herramienta para un ejercicio de clase pero cuando ejecuto  se queda tal que así, alguien sabe porque puede ser?
![Captura de pantalla_2024-07-13_14-25-58](https://github.com/user-attachments/assets/ae5b4519-248c-4020-b2d3-a7f5140d3fd9)

Gracias a todos!

**Comment by ngranade** [comment]
Hola Alloy, te falta pasarle los parametros o la forma de ejecutarse como te indica.

proba con ./evilTrust.sh -m terminal o ./evilTrust.sh -m gui

saludos

**Comment by AlloyB** [comment]
Joder muchas gracias
