### ISSUE TITLE
El personalisado

### ISSUE THREAD

**Issue by R0LO** [s4vitar/evilTrust#8]
Como creo una plantilla personalisada que funcione ?
Clono una con httrack pero no me devuelve credenciales 
Como creo una que funcione ?

**Comment by s4vitar** [comment]
Yo suelo clonarlas con weeman. Una vez clonada me suelo copiar el index.html que crea y lo retoco para que el ACTION esté definido por un script en PHP que yo mismo defino, para indicar que la data que se tramite por POST quiero que se almacene en un fichero.
