### ISSUE TITLE
evilTrust.sh: line 91: ifconfig: command not found

### ISSUE THREAD

**Issue by xdanial** [s4vitar/evilTrust#9]
Me sale ese error al intentar poner el nombre de la interfaz

**Comment by s4vitar** [comment]
Pero eso no tiene que ver con la herramienta, eso es que no tienes la utilidad instalada a nivel de sistema.

> apt install net-tools -y

**Comment by s4vitar** [comment]
Pero eso no tiene que ver con la herramienta, eso es que no tienes la utilidad instalada a nivel de sistema.

>apt install net-tools -y
